### PR TITLE
feat: Add container insights

### PR DESCRIPTION
**Pull request by DrFaust92**
# Description

Add container insights settings + update pre-commit hook version
per: 
https://www.terraform.io/docs/providers/aws/r/ecs_cluster.html#setting
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/deploy-container-insights-ECS.html

### CODE REVIEW

**Comment by EvgeniiProkofevItomych** [comment]
Just wondering why this PR not yet merged?

**Comment by ozbillwang** [comment]
@DrFaust92 

could you add this feature in `complete-ecs` codes as well?

I like this feature, even the default value is false. But I do recommand to enable it in example.

**Comment by DrFaust92** [comment]
@ozbillwang, done.

@antonbabenko , can you take a look at this?

**Comment by antonbabenko** [comment]
Thanks @DrFaust92 !

[v2.3.0](https://github.com/terraform-aws-modules/terraform-aws-ecs/releases/v2.3.0) has been just released.

**Pull request merged**
