### PR TITLE
feat: Add support for restartPolicy 

### LINKED ISSUE #230: Can we support RestartPolicy
## Is your request related to a problem? Please describe.
AWS ECS now supports restart policy to restart a container without restarting the whole tasks.

## Describe the solution you'd like.
Implementation of: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-restart-policy-example.html 

## Describe alternatives you've considered.
None for now i just wait until this has been added.

### PR DESCRIPTION
**Pull request by psantus**
## Description
ECS now supports the ability to restart containers when they crash.

Supporting documentation:
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerRestartPolicy.html 
* https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-ecs-restart-containers-task-relaunch/

## Motivation and Context
Fixes #230

## Breaking Changes

Shouldn't be breaking as older terraform provider versions will just ignore restartPolicy and a default value is provided with enabled = false (default behaviour when it's absent)

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by psantus** [comment]
It now works fine (fixed the validation test on var.restart_policy)

**Comment by psantus** [comment]
@bryantbiggs is the "Optional object type attributes are experimental" fail a problem? I believe it's long been in Terraform core (since 1.3)

**Review by bryantbiggs — APPROVED** [review]

**Comment by psantus** [comment]
Cheers @bryantbiggs. 
Do you have an ETA for v6?

**Comment by RRosalia** [comment]
This is amazing! When will a new tag release be done? So we can start using it?

**Pull request merged**
